version: "3.2"
services:
  database:
    container_name: cms-database
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - database-data:/var/lib/postgresql/data/
    networks:
      - cms
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  migrate:
    container_name: cms-migrate
    image: migrate/migrate
    env_file:
      - docker.env
    networks:
      - cms
    volumes:
      - ./migrations:/migration
    depends_on:
      database:
        condition: service_healthy
        restart: true
    command:
      [
        "-path",
        "./migration",
        "-database",
        "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@cms-database:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=${POSTGRES_SSL}",
        "up",
      ]
  app:
    networks:
      - cms
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
    build: .
    container_name: cms-app
    restart: on-failure:3
    env_file:
      - docker.env
    environment:
      - POSTGRES_HOSTNAME=cms-database
    depends_on:
      database:
        condition: service_healthy
        restart: true
networks:
  cms:
    driver: bridge
volumes:
  database-data:
